/*
 * Copyright 2016 The gRPC Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.grpc;

/**
 * Provides a way to bind instance of service implementation to server.
 * 提供了一种将服务实现实例绑定到服务器的方法。
 *
 * <p>It is used by service's abstract class generated by compiler (eg.:
 * RouteGuideGrpc.RouteGuideImplBase for RouteGuide service) and lets implementation classes to be
 * bind to server.
 * <p> 它由编译器生成的服务抽象类 (例如: RouteGuideGrpc.RouteGuideImplBase for RouteGuide service)
 * 使用，并允许将实现类绑定到服务器。
 *
 * <pre><code>
 * class RouteGuideService extends RouteGuideGrpc.RouteGuideImplBase {
 *   // ...
 * }
 *
 * Server server = ServerBuilder.forPort(1234).addService(new RouteGuideService()).build();
 * </code></pre></p>
 */
public interface BindableService {
  /**
   * Creates {@link ServerServiceDefinition} object for current instance of service implementation.
   * <br>
   * 为服务实现的当前实例创建 {@link ServerServiceDefinition} 对象。
   *
   * @return ServerServiceDefinition object.
   */
  ServerServiceDefinition bindService();
}
